dependencies:
  bme280:
    url: github.com/toitware/bme280-driver
    version: ^1.0.0
  certificate_roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.6.1
  cli:
    url: github.com/toitlang/pkg-cli
    version: ^1.2.0
  dhtxx:
    url: github.com/toitware/toit-dhtxx
    version: ^1.4.0
  ds18b20:
    url: github.com/toitware/toit-ds18b20
    version: ^2.0.0
  font_x11_adobe:
    url: github.com/toitlang/pkg-font-x11-adobe
    version: ^0.1.0
  hc_sr04:
    url: github.com/lask/toit-hc-sr04
    version: ^2.1.0
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.11.0
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.3.4
  morse:
    url: github.com/toitware/toit-morse
    version: ^1.0.6
  mqtt:
    url: github.com/toitware/mqtt
    version: ^2.4.0
  ntp:
    url: github.com/toitlang/pkg-ntp
    version: ^1.0.0
  one_wire:
    url: github.com/toitware/toit-1-wire
    version: ^2.1.1
  pictogrammers_icons:
    url: github.com/toitware/toit-icons-pictogrammers
    version: ^1.0.0
  pixel_display:
    url: github.com/toitware/toit-pixel-display
    version: ^1.6.1
  pixel_strip:
    url: github.com/toitware/toit-pixel-strip
    version: ^0.3.0
  ssd1306:
    url: github.com/toitware/toit-ssd1306
    version: ^1.6.0
  supabase:
    url: github.com/toitware/toit-supabase
    version: ^0.1.0
  telegram:
    url: github.com/floitsch/toit-telegram
    version: ^0.5.2
