name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'yarn'

    - name: Install Dependencies
      env:
        # The existing ci.yml uses a secret here. We may not need it,
        # but we include it to be safe.
        GITHUB_NPM_TOKEN: ${{ secrets.LEON_GITHUB_NPM_PAT }}
      run: |
        npm config set //npm.pkg.github.com/:_authToken=$GITHUB_NPM_TOKEN
        yarn install --frozen-lockfile

    - name: Run tests
      run: yarn test:ci
